config/routes.rb
Rails.application.routes.draw do
  resources :categorias
  
  resources :discos do
    member do
      get 'interesse' => 'discos#interesse' # rota do modal
      get 'enviarmail' => 'discos#enviarmail' # rota para envio do email
      post 'enviarmail' => 'discos#enviarmail' # rota para envio do email
    end
  end

  devise_for :users

  root 'discos#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/categoria.rb
class Categoria < ActiveRecord::Base
  has_many :discos
end

app/models/disco.rb
class Disco < ActiveRecord::Base
  has_attached_file :image, styles: { large:"600x600>", medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  belongs_to :categoria
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categorias_controller.rb
class CategoriasController < ApplicationController
  before_action :set_categoria, only: [:show, :edit, :update, :destroy]

  # GET /categorias
  # GET /categorias.json
  def index
    @categorias = Categoria.all
  end

  # GET /categorias/1
  # GET /categorias/1.json
  def show
  end

  # GET /categorias/new
  def new
    @categoria = Categoria.new
  end

  # GET /categorias/1/edit
  def edit
  end

  # POST /categorias
  # POST /categorias.json
  def create
    @categoria = Categoria.new(categoria_params)

    respond_to do |format|
      if @categoria.save
        format.html { redirect_to @categoria, notice: 'Categoria was successfully created.' }
        format.json { render :show, status: :created, location: @categoria }
      else
        format.html { render :new }
        format.json { render json: @categoria.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categorias/1
  # PATCH/PUT /categorias/1.json
  def update
    respond_to do |format|
      if @categoria.update(categoria_params)
        format.html { redirect_to @categoria, notice: 'Categoria was successfully updated.' }
        format.json { render :show, status: :ok, location: @categoria }
      else
        format.html { render :edit }
        format.json { render json: @categoria.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categorias/1
  # DELETE /categorias/1.json
  def destroy
    @categoria.destroy
    respond_to do |format|
      format.html { redirect_to categorias_url, notice: 'Categoria was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_categoria
      @categoria = Categoria.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def categoria_params
      params.require(:categoria).permit(:name)
    end
end

app/controllers/discos_controller.rb
class DiscosController < ApplicationController
  before_action :set_disco, only: [:show, :edit, :update, :destroy, :interesse, :enviarmail]

  # GET /discos
  # GET /discos.json
  def index
    @discos = Disco.all
  end

  # GET /discos/1
  # GET /discos/1.json
  def show
  end

  def interesse  
  end

  def enviarmail
    # Recebendo valores do formulário do modal
    name = params[:name]
    email = params[:email]
    # Método para enviar email responsável por passar os parâmetros nome do disco, nome e email para a view
    EnviarEmail.send_mail(@disco, name, email).deliver_now
    respond_to do |format|
      format.html {render action: 'show', notice: "Email enviado com sucesso!"}
      format.js
    end
  end

  # GET /discos/new
  def new
    @disco = Disco.new
  end

  # GET /discos/1/edit
  def edit
  end

  # POST /discos
  # POST /discos.json
  def create
    @disco = Disco.new(disco_params)

    respond_to do |format|
      if @disco.save
        format.html { redirect_to @disco, notice: 'Disco was successfully created.' }
        format.json { render :show, status: :created, location: @disco }
      else
        format.html { render :new }
        format.json { render json: @disco.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /discos/1
  # PATCH/PUT /discos/1.json
  def update
    respond_to do |format|
      if @disco.update(disco_params)
        format.html { redirect_to @disco, notice: 'Disco was successfully updated.' }
        format.json { render :show, status: :ok, location: @disco }
      else
        format.html { render :edit }
        format.json { render json: @disco.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /discos/1
  # DELETE /discos/1.json
  def destroy
    @disco.destroy
    respond_to do |format|
      format.html { redirect_to discos_url, notice: 'Disco was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_disco
      @disco = Disco.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def disco_params
      params.require(:disco).permit(:name, :description, :price, :year, :state, :local, :image, :categoria_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categorias_helper.rb
module CategoriasHelper
end

app/helpers/discos_helper.rb
module DiscosHelper
  def number_to_currency_br(number)
    number_to_currency(number, :unit => "R$ ", :separator => ",", :delimiter => ".")
  end
end

app/views/categorias/_form.html.haml
= simple_form_for(@categoria, html: { class: 'form-horizontal' }) do |f|
  - if @categoria.errors.any?
    #error_explanation
      %h2= "#{pluralize(@categoria.errors.count, "error")} prohibited this categoria from being saved:"
      %ul
        - @categoria.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/categorias/edit.html.haml
.col-md-3
  %p.lead Loja de discos
  .list-group
    = link_to categorias_path, class: "list-group-item" do
      %i.fa.fa-plus
      Cadastrar categoria
    = link_to discos_path, class: "list-group-item" do
      %i.fa.fa-music
      Cadastrar discos
    = link_to '#', class: "list-group-item" do
      %i.fa.fa-question-circle
      Sobre

.col-md-9
  %h1 Editing categoria

  = render 'form'

  = link_to 'Show', @categoria
  \|
  = link_to 'Back', categorias_path

app/views/categorias/index.html.haml
%p#notice= notice

.col-md-3
  %p.lead Loja de discos
  .list-group
    = link_to categorias_path, class: "list-group-item" do
      %i.fa.fa-plus
      Cadastrar categoria
    = link_to discos_path, class: "list-group-item" do
      %i.fa.fa-music
      Cadastrar discos
    = link_to '#', class: "list-group-item" do
      %i.fa.fa-question-circle
      Sobre

.col-md-9
  .row
    %h3 Categorias cadastradas
    %ul
      - @categorias.each do |categoria|
        %li
          = categoria.name


  - if user_signed_in?
    .row
      %h2 Administração
      %table.table
        %thead
          %tr
            %th Name
            %th
            %th
            %th

        %tbody
          - @categorias.each do |categoria|
            %tr
              %td= categoria.name
              %td
                = link_to categoria, {title: 'Visualizar', class: "tooltip-js", "data-toggle" => "tooltip", "data-placement" => "top" } do
                  %i.fa.fa-search
              %td
                = link_to edit_categoria_path(categoria), {title: "Editar", class: "tooltip-js", "data-toggle" => "tooltip", "data-placement" => "top" } do
                  %i.fa.fa-edit
              %td
                = link_to categoria, method: :delete, data: { confirm: 'Are you sure?' }, title:"Remover", class: "tooltip-js", "data-toggle" => "tooltip", "data-placement" => "top" do
                  %i.fa.fa-remove

      %br

      = link_to 'New Categoria', new_categoria_path

app/views/categorias/new.html.haml
.col-md-3
  %p.lead Loja de discos
  .list-group
    = link_to categorias_path, class: "list-group-item" do
      %i.fa.fa-plus
      Cadastrar categoria
    = link_to discos_path, class: "list-group-item" do
      %i.fa.fa-music
      Cadastrar discos
    = link_to '#', class: "list-group-item" do
      %i.fa.fa-question-circle
      Sobre

.col-md-9
  %h1 New categoria

  = render 'form'

  = link_to 'Back', categorias_path

app/views/categorias/show.html.haml
%p#notice= notice

.col-md-3
  %p.lead Loja de discos
  .list-group
    = link_to categorias_path, class: "list-group-item" do
      %i.fa.fa-plus
      Cadastrar categoria
    = link_to discos_path, class: "list-group-item" do
      %i.fa.fa-music
      Cadastrar discos
    = link_to '#', class: "list-group-item" do
      %i.fa.fa-question-circle
      Sobre

.col-md-9 
  %p
    %b Name:
    = @categoria.name

  = link_to 'Edit', edit_categoria_path(@categoria)
  \|
  = link_to 'Back', categorias_path

app/views/discos/_form.html.haml
= simple_form_for(@disco, html: { class: 'form-horizontal' }) do |f|
  = f.error_notification
  .form-inputs
    = f.association :categoria, prompt: "Selecione uma categoria"
    = f.input :name
    = f.input :image, as: :file
    = f.input :description
    = f.input :price
    = f.input :year
    = f.input :state, collection: ['Novo', 'Semi novo'], prompt: "Selecione um estado"
    = f.input :local, collection: ['Fortaleza', 'Brasília'], prompt: "Selecione uma cidade"
  .form-actions
    = f.button :submit

app/views/discos/_interesse.html.haml
= simple_form_for @disco, url: enviarmail_disco_path(@disco), method: :post, html: { class: 'form-horizontal form-interessado' } do |f|
  = f.error_notification
  .container-fluid
    .form-inputs
      .form-group
        = label_tag "Nome", nil, class: "control-label"
        = text_field_tag :name, nil, class: "string required form-control"
      .form-group
        = label_tag "Email", nil, class: "control-label"
        = text_field_tag :email, nil, class: "string required form-control"
  .form-actions.pull-right
    %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Close
    = button_tag "Enviar", class: "btn btn-warning" do
      %i.fa.fa-send
      Enviar
  %br
  %br

app/views/discos/edit.html.haml
.col-md-3
  %p.lead Loja de discos
  .list-group
    = link_to categorias_path, class: "list-group-item" do
      %i.fa.fa-plus
      Cadastrar categoria
    = link_to discos_path, class: "list-group-item" do
      %i.fa.fa-music
      Cadastrar discos
    = link_to '#', class: "list-group-item" do
      %i.fa.fa-question-circle
      Sobre

.col-md-9
  %h1 Editing Disco
  = render 'form'
  = link_to 'Show', @disco
  |
  = link_to 'Back', discos_path

app/views/discos/index.html.haml
%p#notice= notice

- if user_signed_in?
  .col-md-3
    %p.lead Loja de discos
    .list-group
      = link_to categorias_path, class: "list-group-item" do
        %i.fa.fa-plus
        Cadastrar categoria
      = link_to discos_path, class: "list-group-item" do
        %i.fa.fa-music
        Cadastrar discos
      = link_to '#', class: "list-group-item" do
        %i.fa.fa-question-circle
        Sobre

  .col-md-9
    .row
      %h2 Administração 

      %table.table
        %thead
          %tr
            %th Categoria
            %th Nome
            %th Imagem
            %th Preço
            %th Ano
            %th Estado de conservação

            %th Local
            %th{:colspan => "3"}
        %tbody
          - @discos.each do |disco|
            %tr
              %td= disco.categoria.name
              %td= disco.name
              %td= image_tag disco.image.url(:thumb)
              %td= number_to_currency_br(disco.price)
              %td= disco.year
              %td= disco.state
              %td= disco.local
              %td
                = link_to disco, {title: 'Visualizar', class: "tooltip-js", "data-toggle" => "tooltip", "data-placement" => "top" } do
                  %i.fa.fa-search
              %td
                = link_to edit_disco_path(disco), {title: "Editar", class: "tooltip-js", "data-toggle" => "tooltip", "data-placement" => "top" } do
                  %i.fa.fa-edit
              %td
                = link_to disco, method: :delete, data: { confirm: 'Are you sure?' }, title:"Remover", class: "tooltip-js", "data-toggle" => "tooltip", "data-placement" => "top" do
                  %i.fa.fa-remove
      %br/

      = link_to 'New Disco', new_disco_path

- else
  .col-md-12
    .row
      - @discos.each do |disco|
        .col-md-4
          = link_to disco, class: "fade-info" do
            .caption
              %h3
                = disco.name
              %p
                R$ #{disco.price}
            = image_tag disco.image.url(:medium), class: "disco fade-info"

            

app/views/discos/interesse.js.haml
$(".modal-body").empty();
$('.modal-body').html('#{escape_javascript(render 'interesse')}');
$("#modal-interesse").modal('show');

app/views/discos/new.html.haml
.col-md-3
  %p.lead Loja de discos
  .list-group
    = link_to categorias_path, class: "list-group-item" do
      %i.fa.fa-plus
      Cadastrar categoria
    = link_to discos_path, class: "list-group-item" do
      %i.fa.fa-music
      Cadastrar discos
    = link_to '#', class: "list-group-item" do
      %i.fa.fa-question-circle
      Sobre

.col-md-9
  %h1 New Disco
  = render 'form'
  = link_to 'Back', discos_path

app/views/discos/show.html.haml
%p#notice= notice

- if user_signed_in?
  .col-md-3
    %p.lead Loja de discos
    .list-group
      = link_to categorias_path, class: "list-group-item" do
        %i.fa.fa-plus
        Cadastrar categoria
      = link_to discos_path, class: "list-group-item" do
        %i.fa.fa-music
        Cadastrar discos
      = link_to '#', class: "list-group-item" do
        %i.fa.fa-question-circle
        Sobre

  .col-md-9      
    %p
      %strong Categoria:
      = @disco.categoria.name

    %p
      %strong Nome:
      = @disco.name
    %p
      %strong Imagem:
      = image_tag @disco.image.url(:medium)

    %p
      %strong Descrição:
      = @disco.description
    %p
      %strong Preço:
      = number_to_currency_br(@disco.price)
    %p
      %strong Ano:
      = @disco.year
    %p
      %strong Estado de conservação:
      = @disco.state
    %p
      %strong Local:
      = @disco.local
    = link_to 'Edit', edit_disco_path(@disco)
    |
    = link_to 'Back', discos_path

- else
  .row
    .col-md-12
      .col-md-7
        .row
          = image_tag @disco.image.url(:large)
        .row
          = link_to interesse_disco_path, {class: 'btn btn-warning pull-right btn-interessado btn-lg', 'data-toggle' => 'modal', 'data-target' => '#modal-show', :remote => true} do
            %i.fa.fa-heart-o 
            Estou interessado!  
      .col-md-5
        .row  
          %p
            %strong Categoria:
            = @disco.categoria.name
          %p
            %strong Nome:
            = @disco.name
          %p
            %strong Descrição:
            = @disco.description
          %p
            %strong Preço:
            = number_to_currency_br(@disco.price)
          %p
            %strong Ano:
            = @disco.year
          %p
            %strong Estado de conservação:
            = @disco.state
          %p
            %strong Local:
            = @disco.local
        .row
          // Aqui ficará o mapa
          .row
            %div{style:'width: 100%;'}
              #gmap{style:'width: 100%; height: 240px;'}  
          %hr

#modal-interesse.modal.fade{:role => "dialog", :tabindex => "-1"}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} &times;
        %h4.modal-title Tenho interesse no disco: #{@disco.name}
      .modal-body


// MAPLACE  COORD(LAT, LON) - FORT -3.7301514, -38.5212008 | BRAS -15.7901514, -47.8812008
:javascript

  var brasilia = [
    {
      lat: -15.7901514,
      lon: -47.8812008,
      title: 'Brasília',
      zoom: 13,
      icon: 'http://maps.google.com/mapfiles/markerB.png',
      animation: google.maps.Animation.DROP
    }
  ];

  var fortaleza = [
    {
      lat: -3.7301514,
      lon: -38.5212008,
      title: 'Fortaleza',
      zoom: 13,
      icon: 'http://maps.google.com/mapfiles/markerA.png',
      animation: google.maps.Animation.DROP
    }
  ];

  var maplace = new Maplace({
    locations: #{(@disco.local == 'Fortaleza' ? 'fortaleza' : 'brasilia')},
    controls_on_map: false,
    draggable: false
  });
  maplace.Load();

app/views/enviar_email/send_mail.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
  </head>
  <body>
    <h1>Olá!</h1>
    <p>
      -------------------------------------------
      <br />
      Estou interessado no disco: <%= @disco.name %>
      <br />
      Meu nome: <%= @name %>
      <br />
      Meu email:  <%= @email %>
      <br />
      -------------------------------------------
    </p>
  </body>
</html>

app/views/enviar_email/send_mail.text.erb
-------------------------------------------
Estou interessado no disco: <%= @disco.name %>
Meu nome: <%= @name %>
Meu email:  <%= @email %>
-------------------------------------------

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title TestAppRails
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    %script{:src => "http://maps.google.com/maps/api/js?sensor=false&libraries=geometry&v=3.7"}
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    %link{:href => "https://fonts.googleapis.com/icon?family=Material+Icons", :rel => "stylesheet"}/
    = csrf_meta_tags
  %body

    .navbar.navbar-default
      .container
        .navbar-header
          = link_to "Catálogo de discos", root_path, class: "navbar-brand"
        %ul.nav.navbar-nav
          %li
            = link_to "Cadastrar", new_user_registration_path
            - if user_signed_in?
              %li
                = link_to "Sair", destroy_user_session_path, method: :delete
            - else 
              %li
                = link_to "Logar", new_user_session_path

        %ul.nav.navbar-nav.navbar-right
          - if user_signed_in?
            %li
              = link_to current_user.email, edit_user_registration_path
          - else
            %li
              %a Bem vindo, Visitante
    .container
      .row
        = yield